service: sls-esbuild

provider:
  name: aws
  region: ${env:REGION, 'ap-south-1'}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x
  memorySize: 256
  iam:
    role:
      name: ${self:custom.base}-role
      statements:
      - Effect: "Deny"
        Action:
        - logs:CreateLogStream
        - logs:PutLogEvents
        Resource:
        - "*"

custom:
  esbuild:
    bundle: true
    minify: false

plugins:
  - serverless-esbuild

package:
  individually: true

functions:
  hello:
    handler: src/handlers/hello/index.handler
    events:
      - http:
          path: /hello
          method: get